version: "3"

services:
  database:
    container_name: database
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-data/:/var/lib/postgresql/data/

volumes:
  db-data:
